default:
  tags: ["docker"]
  image: node:20

stages:
  - test

# -----
# Global variables (can be changed on manual pipelines)
# -----

variables:
  FF_USE_FASTZIP: "true"
  ARTIFACT_COMPRESSION_LEVEL: "fast"
  CACHE_COMPRESSION_LEVEL: "fast"
  FF_SCRIPT_SECTIONS: "true"
  HUSKY: 0

# -----
# Test build on MR
# -----

test_build:
  rules:
    - if: $CI_COMMIT_REF_NAME == "main" || $CI_PIPELINE_SOURCE == "merge_request_event"
  stage: test
  script:
    - mv $ENV .env
    - yarn
    - yarn lint
    - yarn build
    - yarn test
  environment:
    name: test-build
    action: access
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
